import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Link from "next/link";
import { MonitorSmartphone } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { ClerkProvider } from "@clerk/nextjs";
import Auth from "@/components/auth/";
import ReactQuaryProvider from "@/providers/ReactQuary";
import CartDropdown from "@/components/cart";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ads,
}: Readonly<{
  children: React.ReactNode;
  ads: React.ReactNode;
}>) {
  return (
    <ReactQuaryProvider>
      <ClerkProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <main className="flex flex-col justify-between min-h-screen">
              <header className="fixed flex justify-between items-center shadow-xl bg-white px-20 w-full h-20 z-40">
                <div className="flex items-center gap-3">
                  <MonitorSmartphone />
                  <Link href="/" className="font-bold text-2xl">
                    Digital Shop
                  </Link>
                </div>
                <div className="flex items-center gap-2">
                  <Auth />
                  <CartDropdown />
                </div>
              </header>
              <div className="px-20 mt-28">
                {children}
                <Toaster />
              </div>
              <div className="my-10 mx-auto flex justify-center">{ads}</div>
            </main>
          </body>
        </html>
      </ClerkProvider>
    </ReactQuaryProvider>
  );
}
